# 网站设置
title: My shhhhhhit Website
description: Welcome to my gayhub website!
url: "https://sandman6z.github.io"


# 作者信息
author:
  name: Sandman Zhang
  email: zbn0238@163.com

# 导航菜单
navbar_links:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog

# 日期格式
date_format: "%Y-%m-%d"

# Markdown 配置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Permalinks 链接格式
permalink: /:title/:year/:month/:day/


# 主题设置（可选）
theme: jekyll-theme-minimal

# 插件设置（可选）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
